config/routes.rb
Rails.application.routes.draw do

  resources :constatuses
  resources :verifications
  resources :hires
  get 'errors/error_404'

  get 'errors/error_422'

  get 'errors/error_500'

  get '/company/dashboard', to:'home#companydash' , as: 'company_dash'

  get '/dashboard/:id', to:'companies#dashboard', as: 'dashboard'

  resources :searches, path: '/search/'
  mount Ckeditor::Engine => '/ckeditor'
  resources :companies, path: '/company'
  resources :ltypes, except: [:index, :show]
  resources :qtypes, except: [:index, :show]
  resources :qualifications, except: [:index, :show]
  resources :licences, except: [:index, :show]
  resources :workhistories, except: [:index, :show]
  resources :profile, only: [:index, :show], path: '/contractor'

  resources :people do 
    get '/verify', to: 'people#verification_up', as: 'verification', via: :post
  end



  resources :categories
  devise_for :users

  root 'home#index'


  resources :jobs do
    resources :bids, except: [:index]
  end

  get 'settings/user/:id', to: "people#edit", as: "settings_user"
  get 'settings/comapny/:id', to: "companies#edit", as: "settings_company"


end

app/models/person.rb
class Person
  include Mongoid::Document
  include Mongoid::Paperclip
  field :first_name, type: String
  field :middle_name, type: String
  field :last_name, type: String
  field :first_line_address, type: String
  field :city, type: String
  field :country, type: String
  field :post_code, type: String
  field :utr, type: String
  field :mobile_number, type: String
  field :bio, type: String
  field :home_number, type: String
  field :hourly_rate, type: String
  field :car_owner, type: Mongoid::Boolean
  field :approval, type: Mongoid::Boolean
  

  has_mongoid_attached_file :photo_id,
  :styles => {
      :small    => ['100x100#',   :jpg],
      :medium   => ['250x250#',    :jpg],
      :large    => ['500x500#',   :jpg]
    }
  validates_attachment_content_type :photo_id, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  belongs_to :user
  has_many :hire
  has_many :constatuses

  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end


  def address
    "#{first_line_address}#{second_line_address}#{post_code}"
  end

  def basic_local
    "#{city} , #{country}"
  end

  def avatar_medium
    self.photo_id(:medium)
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)
    @person.user = current_user.id

    respond_to do |format|
      if @person.save
        format.html { redirect_to profile_path(current_user), notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to profile_path(current_user), notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(current_user), notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:first_name, :middle_name, :last_name, :city, :country, :post_code, :utr, :mobile_number, :home_number, :car_owner, :photo_id, :bio, :hourly_rate)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="photo_id_field">
    <%= form.label :photo_id %>
    <%= form.file_field :photo_id, id: :person_photo_id %>
  </div>

  <div class="form-group">
    <%= form.label :hourly_rate %>
    <%= form.text_field :hourly_rate, id: :person_hourly_rate, class: "form-control", 'aria-describedby': 'hourlyRateHelp', type: 'number' %>

    <small id="hourlyRateHelp" class="form-text text-muted">
      The National Minimum Wage (NMW) is the minimum wage per hour a worker is entitled to in the United Kingdom. ( £6.70 )
    </small>

  </div>


  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :person_first_name, class: "form-control", 'aria-describedby': 'person_first_name' %>

    <small id="person_first_name" class="form-text text-muted">
      Your Given name as writen on your Photo ID or Passport
    </small>

  </div>


  <div class="form-group">
    <%= form.label :middle_name, "Middle Name (optional)" %>
    <%= form.text_field :middle_name, id: :person_middle_name, class: "form-control", 'aria-describedby': 'person_middle_name' %>

    <small id="person_middle_name" class="form-text text-muted">
      A person's name placed after the first name and before the surname.
    </small>

  </div>


  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :person_last_name, class: "form-control", 'aria-describedby': 'person_last_name' %>

    <small id="person_last_name" class="form-text text-muted">
      Your Surname/Last Name as writen on your Photo ID or Passport
    </small>

  </div>


  <div class="form-group">
    <%= form.label :first_line_address %>
    <%= form.text_field :first_line_address, id: :person_first_line_address, class: "form-control", 'aria-describedby': 'person_first_line_address' %>

    <small id="person_first_line_address" class="form-text text-muted">
      Your Surname/Last Name as writen on your Photo ID or Passport
    </small>

  </div>


  <div class="row">
    <div class="col">

      <div class="form-group">
        <%= form.label :city, "City" %>
        <%= form.text_field :city, id: :person_city, class: "form-control", 'aria-describedby': 'person_city' %>

        <small id="person_city" class="form-text text-muted">
          City [London, Birmingham etc.]
        </small>

      </div>

    </div>

    <div class="col">

      <div class="form-group">
        <%= form.label :country, "Country" %>
        <%= form.text_field :country, id: :person_country, class: "form-control", 'aria-describedby': 'person_country' %>

        <small id="person_country" class="form-text text-muted">
          country [England, Scotland etc.]
        </small>

      </div>

    </div>

  </div>

    <div class="form-group">
      <%= form.label :post_code %>
      <%= form.text_field :post_code, id: :person_post_code, class: "form-control", 'aria-describedby': 'person_post_code' %>

      <small id="person_post_code" class="form-text text-muted">
        Your Current Post Code
      </small>

    </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= form.label :utr, "(UTR) Unique Tax Code" %>
        <%= form.text_field :utr, id: :person_utr, class: "form-control", 'aria-describedby': 'person_utr' %>

        <small id="person_utr" class="form-text text-muted">
          (UTR) Unique Tax Code
        </small>

      </div>

    </div>
    <div class="col">

      <div class="form-group">
        <%= form.label :mobile_number, "Mobile Number" %>
        <%= form.text_field :mobile_number, id: :person_mobile_number, class: "form-control", 'aria-describedby': 'person_mobile_number' %>

        <small id="person_mobile_number" class="form-text text-muted">
          (UTR) Uniqua Refence Number
        </small>

      </div>

    </div>

    <div class="col">

      <div class="form-group">
        <%= form.label :home_number, "Home Number" %>
        <%= form.text_field :home_number, id: :person_home_number, class: "form-control", 'aria-describedby': 'person_home_number' %>

        <small id="person_home_number" class="form-text text-muted">
          Home Number
        </small>

      </div>

    </div>
  </div>


  <div class="form-group">
    <%= form.label :bio %>
    <%= form.text_area  :bio, id: :person_bio, class: "form-control", 'aria-describedby': 'person_bio' %>

    <small id="person_bio" class="form-text text-muted">
      Treat this the same as your cover latter
    </small>

  </div>


  <div class="field">
    <%= form.label :car_owner %>
    <%= form.check_box :car_owner, id: :person_car_owner %>
  </div>


  <div class="actions">
    <%= form.submit "Save", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/people/edit.html.erb
<div class="row show_page">


	<div class="col-md-3">
		<%= render 'home/sidemenu' %>


	</div>

	<div class="col-md-9">

		
		

		<div class="card">
		  <div class="card-header">
		  	<div class="row">
		  		<div class="col">
		  			<h4>
		  				Personal Profile
				    </h4>

		  		</div>
		  	</div>
		    

		  </div>
		  <div class="card-body">

			  	<div class="remove_hr">

					<%= render 'form', person: @person %>

			  	</div>


		  </div>
		</div>

	</div>

</div>




<br>
<br>
<br>
<br>

app/views/people/index.html.erb
<% @people.each do |person| %>
    <%= person.first_name %>
    <%= person.middle_name %>
    <%= person.last_name %>

    <%= person.post_code %>
    <%= person.utr %>
    <%= person.mobile_number %>
    <%= person.home_number %>
    <%= person.car_owner %>
    <%= link_to 'Show', person_path(person) %>
    <%= link_to 'Edit', edit_person_path(person) %>
    <%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @person.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Post code:</strong>
  <%= @person.post_code %>
</p>

<p>
  <strong>Utr:</strong>
  <%= @person.utr %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @person.mobile_number %>
</p>

<p>
  <strong>Home number:</strong>
  <%= @person.home_number %>
</p>

<p>
  <strong>Car owner:</strong>
  <%= @person.car_owner %>
</p>


<%= link_to("Ban", person_verification_path(@person), :confirm => "Are you sure?", :method => :put)%>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>