config/routes.rb
Rails.application.routes.draw do

  resources :constatuses
  resources :verifications
  resources :hires
  get 'errors/error_404'

  get 'errors/error_422'

  get 'errors/error_500'

  get '/company/dashboard', to:'home#companydash' , as: 'company_dash'

  get '/dashboard/:id', to:'companies#dashboard', as: 'dashboard'

  resources :searches, path: '/search/'
  mount Ckeditor::Engine => '/ckeditor'
  resources :companies, path: '/company'
  resources :ltypes, except: [:index, :show]
  resources :qtypes, except: [:index, :show]
  resources :qualifications, except: [:index, :show]
  resources :licences, except: [:index, :show]
  resources :workhistories, except: [:index, :show]
  resources :profile, only: [:index, :show], path: '/contractor'

  resources :people do 
    get '/verify', to: 'people#verification_up', as: 'verification', via: :post
  end



  resources :categories
  devise_for :users

  root 'home#index'


  resources :jobs do
    resources :bids, except: [:index]
  end

  get 'settings/user/:id', to: "people#edit", as: "settings_user"
  get 'settings/comapny/:id', to: "companies#edit", as: "settings_company"


end

app/models/verification.rb
class Verification
  include Mongoid::Document
  field :name, type: String

  has_many :constatuses
end

app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
  before_action :set_verification, only: [:show, :edit, :update, :destroy]

  # GET /verifications
  # GET /verifications.json
  def index
    @verifications = Verification.all
  end

  # GET /verifications/1
  # GET /verifications/1.json
  def show
  end

  # GET /verifications/new
  def new
    @verification = Verification.new
  end

  # GET /verifications/1/edit
  def edit
  end

  # POST /verifications
  # POST /verifications.json
  def create
    @verification = Verification.new(verification_params)

    respond_to do |format|
      if @verification.save
        format.html { redirect_to @verification, notice: 'Verification was successfully created.' }
        format.json { render :show, status: :created, location: @verification }
      else
        format.html { render :new }
        format.json { render json: @verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verifications/1
  # PATCH/PUT /verifications/1.json
  def update
    respond_to do |format|
      if @verification.update(verification_params)
        format.html { redirect_to @verification, notice: 'Verification was successfully updated.' }
        format.json { render :show, status: :ok, location: @verification }
      else
        format.html { render :edit }
        format.json { render json: @verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verifications/1
  # DELETE /verifications/1.json
  def destroy
    @verification.destroy
    respond_to do |format|
      format.html { redirect_to verifications_url, notice: 'Verification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verification
      @verification = Verification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verification_params
      params.require(:verification).permit(:name)
    end
end

app/helpers/verifications_helper.rb
module VerificationsHelper
end

app/views/verifications/_form.html.erb
<%= form_with(model: verification, local: true) do |form| %>
  <% if verification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(verification.errors.count, "error") %> prohibited this verification from being saved:</h2>

      <ul>
      <% verification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :verification_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/verifications/edit.html.erb
<h1>Editing Verification</h1>

<%= render 'form', verification: @verification %>

<%= link_to 'Show', @verification %> |
<%= link_to 'Back', verifications_path %>

app/views/verifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Verifications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @verifications.each do |verification| %>
      <tr>
        <td><%= verification.name %></td>
        <td><%= link_to 'Show', verification %></td>
        <td><%= link_to 'Edit', edit_verification_path(verification) %></td>
        <td><%= link_to 'Destroy', verification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Verification', new_verification_path %>

app/views/verifications/new.html.erb
<h1>New Verification</h1>

<%= render 'form', verification: @verification %>

<%= link_to 'Back', verifications_path %>

app/views/verifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @verification.name %>
</p>

<%= link_to 'Edit', edit_verification_path(@verification) %> |
<%= link_to 'Back', verifications_path %>