config/routes.rb
Rails.application.routes.draw do

  resources :constatuses
  resources :verifications
  resources :hires
  get 'errors/error_404'

  get 'errors/error_422'

  get 'errors/error_500'

  get '/company/dashboard', to:'home#companydash' , as: 'company_dash'

  get '/dashboard/:id', to:'companies#dashboard', as: 'dashboard'

  resources :searches, path: '/search/'
  mount Ckeditor::Engine => '/ckeditor'
  resources :companies, path: '/company'
  resources :ltypes, except: [:index, :show]
  resources :qtypes, except: [:index, :show]
  resources :qualifications, except: [:index, :show]
  resources :licences, except: [:index, :show]
  resources :workhistories, except: [:index, :show]
  resources :profile, only: [:index, :show], path: '/contractor'

  resources :people do 
    get '/verify', to: 'people#verification_up', as: 'verification', via: :post
  end



  resources :categories
  devise_for :users

  root 'home#index'


  resources :jobs do
    resources :bids, except: [:index]
  end

  get 'settings/user/:id', to: "people#edit", as: "settings_user"
  get 'settings/comapny/:id', to: "companies#edit", as: "settings_company"


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def search
		@jobs = Job.all
	end


	def companydash
		@comapny = Company.where(:user_id => current_user.id)
		@hires = Hire.where(:company_id => @company)
	end

end

app/helpers/home_helper.rb
module HomeHelper

	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end

end

app/views/home/_jobsList.html.erb
<div class="card full-width">
  <div class="card-body">

    <a href="{{job.url_link}}">
      <h5 class="card-title">
        <div class="row">
          <div class="col-md-9">
            {{job.title}}
          </div>
          <div class="col-md-3 text-align-right">
            <small>
              {{job.time_ago_json}} 
            </small>
          </div>
        </div>
        
        
      </h5>

      <h6 class="card-subtitle mb-2 text-muted">
        London, United Kingdom <br>
        {{job.priceperhour | currency : '£' }} an hour<br>

        <span class="badge badge-danger">
            Price Fixed
        </span>

        <span class="badge badge-light">
          {{job.category.name}}
        </span>
         
        

      </h6>

      <p class="card-text">
        {{job.stripped_naked | limitTo : 200 }}
        <br>
        <br>
      </p>

    </a>

    
  </div>
</div>

<div class="card bg-light full-width" >
  <div class="card-body">
    <div class="card-text">
        <div class="row">
          <div class="col">
            <small class"text-muted">Hourly Rate</small> <br>
            <h4>
              {{job.priceperhour | currency : '£' }}
            </h4>
          </div>
          <div class="col">
            <small class"text-muted">Number of hours</small> <br>
            <h4>
              {{ job.number_of_hours }}
            </h4>
          </div>
          <div class="col">
            <small class"text-muted">Earn</small> <br>
            <h4 id="calculation_origin">
              {{ 
                job.number_of_hours * job.priceperhour | currency : '£'
              }}
            </h4>
          </div>
        </div>
    </div>

  </div>
</div>

app/views/home/_loginform.html.erb
<div class="container">
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "Sign up", class: "btn btn-success btn-lg btn-block" %>
      </div>
    <% end %>

  <div class="newaccountbox">
    already have an account? <%= link_to "Sign In", new_session_path(resource_name)  %>
  </div>


</div>

app/views/home/_navbar.html.erb
<nav class="navbar mainN">
    <div class="left">
      <a href="<%= root_path %>">
        <div class="brand">
          <!-- <span class="beta">Beta</span> -->
        </div>
  
      </a>
      
        <%= form_for Search.new do |f| %>
      <div class="searchbox">
        <div class="leftOfSearch">
          <i class="fas fa-search"></i>
          <label class="iconBtn" id="DropToggler">
            <i class="fas fa-chevron-down"></i>
          </label>

          <div class="dropdown-menu hidden" id="dropdown-menu">
            <a href="#Find Jobs" class="dropdown-item" id="DropToggler">Find Jobs</a>
            <a href="#Find Contractors" class="dropdown-item" id="DropToggler">Find Contractors</a>
          </div>

        </div>

           <%= f.text_field :name, id: "search", placeholder: "Find Contractor" %>
           
      </div>
       <% end %>
      

    </div>
    <div class="right collapsible">

      <ul class="navbar-right">
        <% if user_signed_in? %>

        <div class="profile_avatar">
          <button id="profileShow">
            <%= image_tag current_user.person.photo_id(:small), class: "cover_image" %>
          </button>
          <div class="ProfileDropDown hidden" id="dropdown-profile">

              <a href="<%= profile_path(current_user)%>" class="dropdown-item" id="DropToggler">
                Profile
              </a>

              <% if current_user.company? %>
                
                <a href="<%= company_path(current_user.company) %>" class="dropdown-item" id="DropToggler">
                    Company Profile
                </a>


                <a href="<%= company_dash_path %>" class="dropdown-item" id="DropToggler">
                  Dashboard
                </a>


              <% end %>

              



              <a href="<%= edit_user_registration_path %>" class="dropdown-item" id="DropToggler">
                Settings
              </a>

              <hr>

              <%= link_to "Sing out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

              <div class="dropdown-divider"></div>

          </div>
        </div>


        
        <% else %>

          <li class="nav-item"> <a class="nav-link" href="#">HOW IT WORKS</a></li>
          <li class="nav-item"><a class="nav-link" href="<%= new_user_session_path %>">LOGIN</a></li>
          <li class="nav-item"><a class="nav-link" href="<%= new_user_registration_path %>">SIGN UP</a></li>
        <% end %>

        <a href="<%= new_job_path %>"> <button class="btn btn-success">Post a Job</button></a>
      </ul>

    </div>


</nav>


<script>
  
  $("#DropToggler").click(function(){
    $("#dropdown-menu").toggleClass("hidden");
  });

  $("#profileShow").click(function(){
    $("#dropdown-profile").toggleClass("hidden");
  });

</script>

app/views/home/_newhires.html.erb
<div class="my-3 p-3 bg-white rounded box-shadow">
  <h6 class="border-bottom border-gray pb-2 mb-0">New Hires</h6>
  <% @hires.each do |h| %>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="<%= h.person.photo_id %>" data-holder-rendered="true">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark"><%= h.job.title %></strong>
        Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
      </p>
    </div>

  <% end %>

  <small class="d-block text-right mt-3">
    <a href="#">All updates</a>
  </small>
</div>

app/views/home/_normal.html.erb
<div class="head_rapper">

	<div class="container">
		<div class="row">
			<div class="col">

				<div class="finbox_home">

					<h2 class="title">Built for the Security Industry</h2>
					<p class="info_content">
						SEBKI is a platform inspired by the way you work. both indivituals and business alike, you can Post and Bid on any Job, manage Job posts, and hire contractors.
					</p>
				</div>

			</div>
			<div class="col">
				<div class="sign_up_box_home">
					<%= render 'home/loginform' %>
				</div>
			</div>
		</div>

	</div>

</div>


<!-- <h2>Hello</h2> -->


<style>
	body {
		background:  white;
	}


	.mainN {
	    background: transparent !important;
	    box-shadow: 0 1px 6px rgba(57, 73, 76, 0.1);
	    width: 100% !important;
	}


</style>



<script>
	$( ".wrapper" ).removeClass( "container" );
	console.log("Removed Class Container")
</script>

app/views/home/_sidemenu.html.erb
<div class="list-group" id="list-tab" role="tablist">

	<% if current_user.person? %>
		

	<a class="list-group-item list-group-item-action" id="list-home-list" href="<%= settings_user_path(current_user.person) %>">Personal Profile</a>

	<% end %>

	<% if current_user.company? %>


	<a class="list-group-item list-group-item-action" id="list-profile-list" href="<%= settings_company_path(current_user.company) %>" >Company Profile</a>

	<% end %>

	<a class="list-group-item list-group-item-action" id="list-messages-list" href="<%= edit_user_registration_path %>">Account</a>
	
	<a class="list-group-item list-group-item-action" id="list-settings-list" href="#list-settings" >Settings</a>

</div>

app/views/home/_signedinuser.html.erb
	<!-- <script>
		var user_id = "<%= current_user.id %>";
		console.log("User_id:" + " " + user_id);
	</script> -->



<div class="search_bar card full-width padding-10 bg-dark text-white">
	<div class="row">
		<div class="col">
			<div class="form-group">
			    <label for="searchtitle">
				    <strong> What </strong>
				</label>
			    <input type="search" class="form-control" id="searchtitle" aria-describedby="searchHelp" placeholder="Search" ng-model="searchTitle.title">
			    <small id="searchHelp" class="form-text">
				    job title, keywords, or company.
				</small>

			</div>
		</div>
		<div class="col">

			<div class="form-group">
			    <label for="searchPostcode">
				    <strong> Where</strong>
				</label>
			    <input type="text" class="form-control" id="searchPostcode" aria-describedby="postcodeHelp" placeholder="SW12 3AB" ng-model="searchTitle.location_postcode" ng-model="searchArea.location_postcode">
			    <small id="searchHelp" class="form-text">city or postcode</small>
			</div>

		</div>
	</div>
</div>


<br>
<br>

<div class="row">
	<div class="col-md-8">

		<div class="jobs_listing" ng-controller="jobsController">
			<div class="animated bounceInLeft" ng-repeat="job in filterdShows = ( jobsList | orderBy: 'created_at':true| filter:searchTitle | filter:searchArea )" >
				<%= render 'home/jobsList' %>
				<br> <br>
			</div>
		</div>

	</div>
	<div class="col-md-4">



		<div class="card bg-light full-width text-align-center">
      <div class="container">
      	<br><br>
        <h1 class="display-2 text-align-center">
          <i class="fas fa-clipboard"></i>
        </h1>
        <p class="lead">
          Wish to post a job like this?
        </p>

	        <a href="<%= new_job_path %>"
	        	class="btn btn-apply-round btn-lg btn-block">

	        	Post a Job

	        </a>
      	<br><br>

      </div>
    </div>

	</div>
</div>

app/views/home/companydash.html.erb
<div class="card full-width">

<br>
<div class="container">
<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">New Hires</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">All Bidders</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">OpenJobs</a>
  </li>
</ul>

</div>
</div>

<br><br>


<div class="container">
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
  	New Hires List
  </div>
  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">All Bids</div>
  <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">Open Jobs</div>
</div>


</div>
<br>

app/views/home/index.html.erb
<%# if user_signed_in? %>


<%#= render 'home/signedinuser' %>

<%# else %>

<%#= render 'home/normal' %>


<%# end %>



<%= render 'home/normal' %>