config/routes.rb
Rails.application.routes.draw do

  resources :constatuses
  resources :verifications
  resources :hires
  get 'errors/error_404'

  get 'errors/error_422'

  get 'errors/error_500'

  get '/company/dashboard', to:'home#companydash' , as: 'company_dash'

  get '/dashboard/:id', to:'companies#dashboard', as: 'dashboard'

  resources :searches, path: '/search/'
  mount Ckeditor::Engine => '/ckeditor'
  resources :companies, path: '/company'
  resources :ltypes, except: [:index, :show]
  resources :qtypes, except: [:index, :show]
  resources :qualifications, except: [:index, :show]
  resources :licences, except: [:index, :show]
  resources :workhistories, except: [:index, :show]
  resources :profile, only: [:index, :show], path: '/contractor'

  resources :people do 
    get '/verify', to: 'people#verification_up', as: 'verification', via: :post
  end



  resources :categories
  devise_for :users

  root 'home#index'


  resources :jobs do
    resources :bids, except: [:index]
  end

  get 'settings/user/:id', to: "people#edit", as: "settings_user"
  get 'settings/comapny/:id', to: "companies#edit", as: "settings_company"


end

app/models/company.rb
class Company
  include Mongoid::Document
  include Mongoid::Slug
  field :name, type: String
  field :number, type: String
  field :first_line, type: String
  field :city, type: String
  field :country, type: String
  field :postcode, type: String
  field :phone_number, type: String
  field :Work_number, type: String
  field :created_at, type: String
  field :updated_at, type: String
  slug :name


  before_create :create_time
  before_update :updated_time


  def create_time
  	self.created_at = Time.now
  end

  def updated_time
  	self.updated_at = Time.now
  end


  belongs_to :user
  has_many :hire

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :dashboard]
  before_action :set_relatable, only: [:show, :dashboard]

  def index
    @companies = Company.all
  end

  def show
  end

  def new
    @company = Company.new
  end

  def dashboard
  end


  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.user = current_user.id

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def set_relatable
      @jobs = Job.where(:user_id => @company.user_id)
      @bids = Bid.where(:user_id => @company.user_id)
    end

    def company_params
      params.require(:company).permit(:name, :number, :first_line, :city, :country, :postcode, :phone_number, :Work_number)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :name, "Company name" %>
    <%= form.text_field :name, id: :company_name, class: "form-control", 'aria-describedby': 'name' %>
    
    <small id="hourlyRateHelp" class="form-text text-muted">
      The name of your company
    </small>

  </div>


  <div class="form-group">
    <%= form.label :number, "Company number" %>
    <%= form.text_field :number, id: :company_number, class: "form-control", 'aria-describedby': 'companynumber' %>
    
    <small id="companynumber" class="form-text text-muted">
      Company Registration Number
    </small>

  </div>


  <div class="form-group">
    <%= form.label :first_line, "First line of address" %>
    <%= form.text_field :first_line, id: :company_first_line, class: "form-control", 'aria-describedby': 'company_first_line' %>
    
    <small id="company_first_line" class="form-text text-muted">
      The first Line of you address
    </small>

  </div>

  <div class="form-group">
    <%= form.label :city, "City" %>
    <%= form.text_field :city, id: :company_city, class: "form-control", 'aria-describedby': 'company_city' %>
    
    <small id="company_city" class="form-text text-muted">
      City e.g LONDON
    </small>

  </div>


  <div class="form-group">
    <%= form.label :country, "Country" %>
    <%= form.text_field :country, id: :company_country, class: "form-control", 'aria-describedby': 'company_country' %>
    
    <small id="company_country" class="form-text text-muted">
      Country
    </small>

  </div>


  <div class="form-group">
    <%= form.label :postcode %>
    <%= form.text_field :postcode, id: :company_postcode, class: "form-control", 'aria-describedby': 'company_postcode' %>
    
    <small id="company_postcode" class="form-text text-muted">
      Post Code e.g SW12 3AB
    </small>

  </div>


  <div class="form-group">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :company_phone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Work_number %>
    <%= form.text_field :Work_number, id: :company_Work_number, class: "form-control" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/companies/_newhires.html.erb
<div class="my-3 p-3 bg-white rounded box-shadow">
  <h6 class="border-bottom border-gray pb-2 mb-0">New Hires</h6>
<!--   <%# @company.each do |h| %>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="<%#= h.person.photo_id %>" data-holder-rendered="true">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark"><%#= h.job.title %></strong>
        Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
      </p>
    </div>

  <%# end %> -->

  <small class="d-block text-right mt-3">
    <a href="#">All updates</a>
  </small>
</div>

app/views/companies/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col card">
      Jobs <br>
      <h3><%= @jobs.count %></h3>
    </div>
    <div class="col card">
      Hire <br>
      <h3><%=  @company.hire.count %></h3>
    </div>
    <div class="col card bg-light ">
      Total Cost <br>
      <h3>£234,648</h3>
    </div>
  </div>
</div>

<br><br>

<ul class="pricedItems">

  <%= @jobs.sum(:price) %>
  <% @jobs.each do |j| %>
    <li data-price="<%= j.price %>" >
      <%= j.price %>
    </li>
  <% end %>

  <label class="result"></label>
</ul>


<script>
  
  const priceNodes = Array.from(document.querySelectorAll('[data-price]'));
  const price = priceNodes
    .map(node => node.dataset.price );

  console.log(price)


</script>

<div class="card full-width">

<br>
<div class="container">
<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">New Hires</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">All Bidders</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">OpenJobs</a>
  </li>
</ul>

</div>
</div>

<br><br>

<div class="container">
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
    
    <%= render 'companies/newhires' %>

  </div>
  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">All Bids</div>
  <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">Open Jobs</div>
</div>



</div>
<br>

app/views/companies/edit.html.erb
<div class="row show_page">


	<div class="col-md-3">
		<%= render 'home/sidemenu' %>

	</div>

	<div class="col-md-9">

		<div class="card">
		  <div class="card-header">
		  	<div class="row">
		  		<div class="col">
		  			<h4>
		  				Company Profile
				    </h4>

		  		</div>
		  	</div>
		    

		  </div>
		  <div class="card-body">
			  	<div class="remove_hr">
					<%= render 'form', company: @company %>
			  	</div>
		  </div>
		</div>

		
		

	</div>
</div>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>First line</th>
      <th>City</th>
      <th>Country</th>
      <th>Postcode</th>
      <th>Phone number</th>
      <th>Work number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.number %></td>
        <td><%= company.first_line %></td>
        <td><%= company.city %></td>
        <td><%= company.country %></td>
        <td><%= company.postcode %></td>
        <td><%= company.phone_number %></td>
        <td><%= company.Work_number %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<div class="card_wrapper">

<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

</div>

app/views/companies/show.html.erb
<div class="row">
  <div class="col-md-4">
    
    <div class="card full-width">
      <div class="card-body">
        <br> <br>
        <h5 class="card-title">
          <%= @company.name %>
          <br>
          <small>
            <span class="text-secondary">
              <%= @company.number %>
            </span>
          </small>
      </h5>
        <p class="card-text">

          <p>
            <strong>City:</strong>
            <%= @company.city %>
          </p>

          <p>
            <strong>Country:</strong>
            <%= @company.country %>
          </p>

          <p>
            <strong>Postcode:</strong>
            <%= @company.postcode %>
          </p>

          <p>
            <strong>Phone number:</strong>
            <%= @company.phone_number %>
          </p>

          <p>
            <strong>Work number:</strong>
            <%= @company.Work_number %>
          </p>

        </p>

      </div>
    </div>


    <div class="card bg-light full-width" >
      <div class="card-body">
        <h5 class="card-title">Statistics</h5><hr>
        <div class="card-text">
            <div class="row">
              <div class="col">
                <small class"text-muted">Jobs</small> <br>
                <h4><%= @jobs.count %></h4>
              </div>
              <div class="col">
                <small class"text-muted">Bids</small> <br>
                <h4><%=  @bids.count %></h4>

              </div>

              <div class="col">
                <small class"text-muted">Hires</small> <br>
                <h4><%=  @company.hire.count %></h4>
                
              </div>

            </div>
        </div>


      </div>
    </div>

  </div>
  <div class="col">

    <% @jobs.each do |job| %>


      <div class="job">
        <div class="card full-width">
          <div class="card-body">

            <a href="<%= job_path(job) %>">
              <h5 class="card-title">
                <div class="row">
                  <div class="col-md-9">
                    <%= job.title %>
                  </div>
                  <div class="col-md-3 text-align-right">
                    <small>
                      <%= time_ago_in_words(job.timeago)%> <i class="far fa-clock"></i> 
                    </small>
                  </div>
                </div>
                
                
              </h5>

              <h6 class="card-subtitle mb-2 text-muted">
                <%= job.user.company.city %>, <%= job.user.company.country %> <br>
                £<%= job.priceperhour %> an hour<br>
                
                  <% if job.fixedPrice == true %>
                    <span class="badge badge-danger">
                      Price Fixed
                    </span>
                  <% elsif job.fixedPrice == false %>
                    <span class="badge badge-success ">
                      Negotiable 
                    </span>
                  <% end %>

                <span class="badge badge-light">
                  <%= job.category.name %>
                </span>
                 
                

              </h6>

              <p class="card-text">
                <%= truncate(job.stripped_naked, length: 200) %>
                <br>
                <br>
              </p>

            </a>

            <% if user_signed_in? %>
              <% if current_user.id == job.user_id %>
                <!-- <hr> -->
                <%#= link_to 'Show', job, class: 'btn btn-primary' %>
                <%#= link_to 'Edit', edit_job_path(job), class: 'btn btn-warning' %>
                <%#= link_to 'Destroy', job, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            <% end %>

            
          </div>
        </div>

        <div class="card bg-light full-width" >
          <div class="card-body">
            <div class="card-text">
                <div class="row">
                  <div class="col">
                    <small class"text-muted">Hourly Rate</small> <br>
                    <h4>£<%= job.priceperhour %>.00</h4>
                  </div>
                  <div class="col">
                    <small class"text-muted">Number of hours</small> <br>
                    <h4><%= job.number_of_hours %></h4>
                  </div>
                  <div class="col">
                    <small class"text-muted">Cost</small> <br>
                    <h4 id="calculation_origin">
                      £<%= (job.priceperhour.to_f * job.number_of_hours.to_f)%>
                    </h4>
                  </div>
                </div>
            </div>

          </div>
        </div>


        </div>

        <br>


            <% job.bids.each do |bid|%>
              <%= bid.id %>
            <% end %>  
            

    <% end %>
    
  </div>
</div>





<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>